export const products = [
  {
    id: 1,
    name: 'Test product',
    price: 200,
    purchases: 3000,
    rating: 65,
    imageUrl: 'assets/ph.jpg',
  },
  {
    id: 2,
    name: 'Test product',
    price: 200,
    purchases: 3000,
    rating: 65,
    imageUrl: 'assets/ph1.jpg',
  },
  {
    id: 3,
    name: 'Test product',
    price: 200,
    purchases: 3000,
    rating: 65,
    imageUrl: 'assets/ph2.jpg',
  },
  {
    id: 4,
    name: 'Test product',
    price: 200,
    purchases: 3000,
    rating: 65,
    imageUrl: 'assets/ph3.jpg',
  },
  {
    id: 5,
    name: 'Test product',
    price: 200,
    purchases: 3000,
    rating: 65,
    imageUrl: 'assets/ph4.jpg',
  },
];
